# .github/workflows/harvest.yml
name: Daily PyPI harvest
on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ---------- install the required packages ----------
      - name: Install dependencies
        run: pip install --quiet feedparser requests       # <─ new step

      # ---------- run your script ----------
      - name: Run harvester
        run: python scripts/harvest.py                    # adjust path if needed

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main
          commit_message: 'ci: daily PyPI update'
          pull_strategy: REBASE        # or: force_with_lease: true
