name: Daily PyPI harvest
on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:

permissions:            # gives the default GITHUB_TOKEN write scope
  contents: write        # <-- required
  id-token: read

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true     # token stays in ~/.git-credentials

      # … install deps, run harvester …
      - name: Rebase onto latest main
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Auto-commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        env:                         # be explicit: use the same token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main
          commit_message: "ci: daily PyPI update"
          pull_strategy: FETCH_REBASE
