# .github/workflows/harvest.yml
name: Daily PyPI harvest

on:
  schedule:
    - cron: '17 2 * * *'     # 02:17 UTC every day
  workflow_dispatch:

permissions:
  contents: write            # allow the job to push commits

jobs:
  harvest:
    runs-on: ubuntu-latest

    steps:
    # --- 1. check out the real branch, not detached ---
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0        # full history
        persist-credentials: true

    # --- 2. set up Python & run your harvester ---
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    - name: Install deps
      run: pip install -r requirements.txt --quiet --retries 6 --timeout 30

    - name: Run harvester
      run: python harvest.py            # or collect_pypi.py

    # --- 3. commit & re-base-then-push ---
    - name: Commit updated data
      uses: stefanzweifel/git-auto-commit-action@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: main
        commit_message: 'ci: daily PyPI update'
        pull_strategy: FETCH_REBASE      # <-- key line: rebases before push
