# .github/workflows/harvest.yml
name: Daily PyPI harvest

on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/setup-python@v5   # cache parameter removed
        with:
          python-version: '3.12'

      # (skip pip install entirely if you have no deps)
      # - name: Install deps
      #   run: pip install -r requirements.txt

      - name: Run harvester
        run: python scripts/harvest.py

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: main
          commit_message: 'ci: daily PyPI update'
          pull_strategy: REBASE
